language: ruby
cache: bundler
rvm:
- 2.2.0
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- psql -c 'create database aluxure_test;' -U postgres
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: VNsiYhF17lQ2P4ML6bsoeMUW81auvD/YbM0oRyItz4qSsdwMChadSxXQOrkigPJbMMxIYCM1qTNRVsOxtjXSjXZgjCRiJi3FZDv0TchLEHt2L9F4b257kvfXkuGZ9QQPGENBLOaTbK712tiSqP4IX65IPH89ba9ZC6dhZPRxKohHpmjP4+lFPzY2ZJhgURZRSZEOu4huv4RGmEm+M0wG8n8mA+yOf0GdN7A5XvbyVR7FKNsMKKsRjMwTKbli3BmsL1rsrPGP1B4DpxNrl3QUhkVGQ9APNcs5wx0Vwq8r9OMkIA+QiiWs8Jo5iixFUT0YTbg+APzbUrCyepMp1+/TJFNIc44wVxydSbw7IvRQ4jASTZwNwldUp2saKq6QBNL6cl5PT3UD8QF7/WJjbA8FQWVDeOYEA3rZGxBMcHB846eAW4mHZTcbJL9COiYdHkec8r9PUCLXZH9DjPJ6QZaLNR0PFoTiIrRFubOMWQE+tzX6EXIRaHbk8SJ0w5nsF6PppUaLVjjJH/fBjfCjjPdIUoZwZH3t8YTbFEXK+kzubCrOq6ZWx7U0mER0r1hiTcYJhkZq1kUzTgNye2Ql4JJz8OM5ouiJjNksP+/w7hMyJ2BJQlUXXu6wd+0VrHEAl4xbYxII0x5zVWl8sQvlY1PEZKcjxvuiOcUCFY401xQ+RjE=
  app: aluxure
  strategy: git
  run:
  - rake db:migrate
  - restart
notifications:
  slack:
    secure: fJHDXwd5icMGN13QZ5F9K7f7Cz1WYF3h3+EM6pPIMLevpirfUQKh/8O7CzCYSXSZBH+jNN+cvoiE2V7U5M7Dw1CmFCHsdQoVqwslU9PvWA8nuCnQ9PQfcNd5qqEWlaZbmOj5BtdPriIoMPcdmXaDTyHhbSoGE/qZFAEFD3Q4AdAxu21U6kbxJyNVIWczjBzUJZ4QHfftGJO8acEha9MdbmxiIO9h+YUTydAyKA4e7SAnfaCPYzyfqv0RVVPzbKQIgxExXqzP8cVOaXMuKltHvKmYhOdEesicvZ5TJ/Pi7eBUpP9+4tPObIT6NjPhD8RyRjJaJOxv+WCP+7DhFqTFlQOJYzjQrZ1uyekRr4g0Ht0EAc8Gw8i+9SDT57SC39bSqcrFsblBiy5bRNiwVh9WO4dTVIyyFFmuPJWnE3k+171gjPkOKvjg7LPnc1QVmKko5eyoAPXYcPZFjdp6bjRS7CMq2PXfBaAR4E2OvTwI48s9TEsbx/x3n5RpDFnu/VcpMPdM7NQpyXHuroIkQrTiamKNOUuYy7lTT1dR9Gz8xQZOvm58eNF1t5adk8nRcCBtBtgMDDtl/QMDHfArK8XiDgXCCL8gOjQ/6EF7twMP2FntWWxnnlFfFV248mmzQLbmYQojM9jstA9qPKUSqtAKoWEsUVnfGWjXRAz4G4zTDMk=
=======
language: ruby
cache: bundler
rvm:
- 2.2.0
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- psql -c 'create database aluxure_test;' -U postgres
services:
- postgresql
deploy:
  provider: heroku
  api_key:
    secure: VNsiYhF17lQ2P4ML6bsoeMUW81auvD/YbM0oRyItz4qSsdwMChadSxXQOrkigPJbMMxIYCM1qTNRVsOxtjXSjXZgjCRiJi3FZDv0TchLEHt2L9F4b257kvfXkuGZ9QQPGENBLOaTbK712tiSqP4IX65IPH89ba9ZC6dhZPRxKohHpmjP4+lFPzY2ZJhgURZRSZEOu4huv4RGmEm+M0wG8n8mA+yOf0GdN7A5XvbyVR7FKNsMKKsRjMwTKbli3BmsL1rsrPGP1B4DpxNrl3QUhkVGQ9APNcs5wx0Vwq8r9OMkIA+QiiWs8Jo5iixFUT0YTbg+APzbUrCyepMp1+/TJFNIc44wVxydSbw7IvRQ4jASTZwNwldUp2saKq6QBNL6cl5PT3UD8QF7/WJjbA8FQWVDeOYEA3rZGxBMcHB846eAW4mHZTcbJL9COiYdHkec8r9PUCLXZH9DjPJ6QZaLNR0PFoTiIrRFubOMWQE+tzX6EXIRaHbk8SJ0w5nsF6PppUaLVjjJH/fBjfCjjPdIUoZwZH3t8YTbFEXK+kzubCrOq6ZWx7U0mER0r1hiTcYJhkZq1kUzTgNye2Ql4JJz8OM5ouiJjNksP+/w7hMyJ2BJQlUXXu6wd+0VrHEAl4xbYxII0x5zVWl8sQvlY1PEZKcjxvuiOcUCFY401xQ+RjE=
  app: aluxure
  strategy: git
  run:
  - rake db:migrate
  - restart
notifications:
  slack:
    secure: fJHDXwd5icMGN13QZ5F9K7f7Cz1WYF3h3+EM6pPIMLevpirfUQKh/8O7CzCYSXSZBH+jNN+cvoiE2V7U5M7Dw1CmFCHsdQoVqwslU9PvWA8nuCnQ9PQfcNd5qqEWlaZbmOj5BtdPriIoMPcdmXaDTyHhbSoGE/qZFAEFD3Q4AdAxu21U6kbxJyNVIWczjBzUJZ4QHfftGJO8acEha9MdbmxiIO9h+YUTydAyKA4e7SAnfaCPYzyfqv0RVVPzbKQIgxExXqzP8cVOaXMuKltHvKmYhOdEesicvZ5TJ/Pi7eBUpP9+4tPObIT6NjPhD8RyRjJaJOxv+WCP+7DhFqTFlQOJYzjQrZ1uyekRr4g0Ht0EAc8Gw8i+9SDT57SC39bSqcrFsblBiy5bRNiwVh9WO4dTVIyyFFmuPJWnE3k+171gjPkOKvjg7LPnc1QVmKko5eyoAPXYcPZFjdp6bjRS7CMq2PXfBaAR4E2OvTwI48s9TEsbx/x3n5RpDFnu/VcpMPdM7NQpyXHuroIkQrTiamKNOUuYy7lTT1dR9Gz8xQZOvm58eNF1t5adk8nRcCBtBtgMDDtl/QMDHfArK8XiDgXCCL8gOjQ/6EF7twMP2FntWWxnnlFfFV248mmzQLbmYQojM9jstA9qPKUSqtAKoWEsUVnfGWjXRAz4G4zTDMk=
